name: lib-api

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/lib-api.yaml'
      - 'packages/frontend/lib-api/**'

  pull_request:
    branches: [ main ]
    paths:
      - '.github/workflows/lib-api.yaml'
      - 'packages/frontend/lib-api/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: yarn install
      - name: Run linter
        run: yarn workspace lib-api lint
      - name: Run unit tests
        run: yarn workspace lib-api test:unit
